### ISSUE TITLE
Đối tượng sử dụng?

### ISSUE THREAD

**Issue by hhaiwzz** [nganlamsong/pokemon#1]
*Đối tượng hướng tới là những người nào?*

Độ tuổi?
Mức độ am hiểu về pokemon?
Là hoạ sĩ?
Yêu thích nghệ thuật?
...

**Comment by nganlamsong** [comment]
Độ tuổi: cỡ như mình thôi, khoảng 17-25, do vậy nhìn cái design chững chạc, hiện đại xíu...
Mức độ am hiểu pokemon: khá, ít nhất thì cũng biết con đó type gì, name gì, nên nhiều thông tin cũng không còn cần thiết nữa, vài cái chính quan trọng được quan tâm nhất là được rồi.
Ừ: mà thật ra là ai cũng đc, không nhất định phải thích vẽ, có thể là một đứa trẻ nào đó muốn xem con pkm mà nó yêu thích ở những góc độ khác nhau, mình chỉ approve mấy cái hình có chất lượng và ngon ngon tí, chứ không phải hình nào cũng được.

**Comment by hhaiwzz** [comment]
Ok!
